# Generated by Django 3.2.16 on 2022-11-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addcriminalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('carea', models.CharField(max_length=800)),
                ('ctype', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image')),
                ('bnname', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('doorno', models.CharField(max_length=50)),
                ('stname', models.CharField(max_length=200)),
                ('villcit', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('contactnumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnname', models.CharField(max_length=100)),
                ('bpass', models.CharField(max_length=100)),
                ('barea', models.CharField(max_length=800)),
                ('profile', models.ImageField(upload_to='image')),
                ('nopolice', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='chatregg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('time_h_m_s', models.CharField(max_length=15)),
                ('dchatt', models.CharField(max_length=2000)),
                ('fromm', models.CharField(max_length=10)),
                ('too', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=2000)),
                ('date', models.CharField(max_length=15)),
                ('time_h_m_s', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='complaint_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('carea', models.CharField(max_length=800)),
                ('wip', models.CharField(max_length=500)),
                ('detail', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='image')),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnname', models.CharField(max_length=100)),
                ('crimename', models.CharField(max_length=100)),
                ('crimearea', models.CharField(max_length=1000)),
                ('value', models.CharField(max_length=10)),
                ('files', models.FileField(upload_to='file')),
            ],
        ),
        migrations.CreateModel(
            name='Missing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('perno', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('missedarea', models.CharField(max_length=1000)),
                ('my_content', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='register_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=20)),
            ],
        ),
    ]
